spring:
  application:
    name: eureka-server

server:
  port: ${PORT:8010}

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false